[project]
name = "nisaa"
version = "0.1.0"
description = ""
authors = [
    {name = "priyanshu",email = "priyanshu.sahu@nzminds.com"}
]
readme = "README.md"
requires-python = ">=3.8"
dependencies = [
    "fastapi>=0.104.0",
    "uvicorn[standard]>=0.24.0",
    "python-dotenv>=1.0.0",
    "requests (<2.32)",
    "python-multipart (==0.0.20)",
]

[tool.poetry]
packages = [{include = "nisaa", from = "src"}]

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
